# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CocktailRecipes/recipeswindow.ui'
#
# Created: Tue Aug 18 00:29:45 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RecipesWindow(object):
    def setupUi(self, RecipesWindow):
        RecipesWindow.setObjectName(_fromUtf8("RecipesWindow"))
        RecipesWindow.resize(800, 600)
        RecipesWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralWidget = QtGui.QWidget(RecipesWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lineEdit = QtGui.QLineEdit(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(256, 0))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout.addWidget(self.lineEdit)
        self.label = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.cocktailListWidget = QtGui.QListWidget(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cocktailListWidget.sizePolicy().hasHeightForWidth())
        self.cocktailListWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        self.cocktailListWidget.setFont(font)
        self.cocktailListWidget.setObjectName(_fromUtf8("cocktailListWidget"))
        self.verticalLayout.addWidget(self.cocktailListWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line = QtGui.QFrame(self.centralWidget)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.titleLabel = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setText(_fromUtf8(""))
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName(_fromUtf8("titleLabel"))
        self.verticalLayout_2.addWidget(self.titleLabel)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.ingredientsBox = QtGui.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ingredientsBox.setFont(font)
        self.ingredientsBox.setObjectName(_fromUtf8("ingredientsBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.ingredientsBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.scrollArea = QtGui.QScrollArea(self.ingredientsBox)
        self.scrollArea.setMinimumSize(QtCore.QSize(433, 0))
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 457, 182))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ingredientsLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ingredientsLabel.sizePolicy().hasHeightForWidth())
        self.ingredientsLabel.setSizePolicy(sizePolicy)
        self.ingredientsLabel.setMinimumSize(QtCore.QSize(433, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.ingredientsLabel.setFont(font)
        self.ingredientsLabel.setText(_fromUtf8(""))
        self.ingredientsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.ingredientsLabel.setWordWrap(True)
        self.ingredientsLabel.setObjectName(_fromUtf8("ingredientsLabel"))
        self.verticalLayout_8.addWidget(self.ingredientsLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.verticalLayout_5.addWidget(self.ingredientsBox)
        self.verticalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.preparationBox = QtGui.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.preparationBox.setFont(font)
        self.preparationBox.setObjectName(_fromUtf8("preparationBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.preparationBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.scrollArea_2 = QtGui.QScrollArea(self.preparationBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(433, 0))
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 457, 182))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.preparationLabel = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preparationLabel.sizePolicy().hasHeightForWidth())
        self.preparationLabel.setSizePolicy(sizePolicy)
        self.preparationLabel.setMinimumSize(QtCore.QSize(433, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.preparationLabel.setFont(font)
        self.preparationLabel.setText(_fromUtf8(""))
        self.preparationLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.preparationLabel.setWordWrap(True)
        self.preparationLabel.setObjectName(_fromUtf8("preparationLabel"))
        self.verticalLayout_10.addWidget(self.preparationLabel)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.addWidget(self.scrollArea_2)
        self.verticalLayout_6.addWidget(self.preparationBox)
        self.verticalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        RecipesWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(RecipesWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        RecipesWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(RecipesWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        RecipesWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(RecipesWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        RecipesWindow.setStatusBar(self.statusBar)

        self.retranslateUi(RecipesWindow)
        QtCore.QMetaObject.connectSlotsByName(RecipesWindow)

    def retranslateUi(self, RecipesWindow):
        RecipesWindow.setWindowTitle(_translate("RecipesWindow", "Cocktail Recipes", None))
        self.label.setText(_translate("RecipesWindow", "Cocktails List", None))
        self.ingredientsBox.setTitle(_translate("RecipesWindow", "Ingredients", None))
        self.preparationBox.setTitle(_translate("RecipesWindow", "Preparation", None))

